### ISSUE TITLE
Incorrect mangling using the spline method

### ISSUE THREAD

**Issue by RobFirth** [UoS-SNe/CoCo#5] opened 2017-01-25 18:41 UTC
Filters that have very close effective wavelengths (<~100 \AA) cause the mangling spline to mess up because exaggerated gradients. Possibly flag a warning when this happens? Or add a default behaviour to pick one over the other

**Comment by SzymonPrajs** [comment] 2017-02-08 16:56
I have a strong suspicion that the cause of this issue is the difference photometric systems used for `BVRI` and `griz` filters. I run a test on `SN2011dh` where I used `gri` and and `Bri` filter combinations getting a very wrong looking result in the second case. Despite `B` and `g` being very close to each other in wavelength space `LCFit` gives them very different fluxes. Issue #11 needs to be implemented first before any further testing.

**Comment by SzymonPrajs** [comment] 2017-03-16 11:58
This has been temporarily fixed in v0.6.0 by using linear mangling instead of splines.  In v0.7.0 we need to find a more permanent solution.

**Comment by SzymonPrajs** [comment] 2017-05-03 16:32
This is a an issue that just won't go away. At the moment we reverted into a linear function for mangling which is very suboptimal. Fix it @SzymonPrajs!

**Comment by SzymonPrajs** [comment] 2017-05-25 17:25
Mangling now appears to be working correctly for a few test SN. The issue was caused by a low number of live points used when running `MultiNest` fitting routines causing the fits to fall into local minima.

**Closed as completed by SzymonPrajs** 2017-05-25 17:25 UTC
Labels: bug, enhancement
